# backend:
#   name: test-repo
#   branch: master

backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: "/static/img"
public_folder: "/img"
collections:
  - name: dataObituarios
    label: Obituarios
    identifier_field: nombre
    extension: yml
    folder: "/src/data/dataObituarios/obituarios"
    create: true
    preview: false
    fields:
      - label: "Nombre"
        name: "nombre"
        widget: string
      - label: Fotografía
        name: foto
        widget: image
        required: false
      - label: Fecha de Fallecimiento
        name: fechaFin
        widget: date
        required: false
      - label: Epitafio
        name: epitafio
        widget: text
        required: false
      - label: Evento de Misa
        name: misa
        widget: object
        required: false
        fields:
          - label: Fecha y Hora de la Misa
            name: fechaMisa
            widget: datetime
          - label: URL del lugar de la misa
            name: urlLugarMisa
            widget: string
            default: "https://www.google.com/maps/place/Prever+-+Sal%C3%B3n+Velatorio/@-17.7941441,-63.16884,16z/data=!4m5!3m4!1s0x93f1e85d62ea77cb:0xfd9e12d454893aca!8m2!3d-17.7943484!4d-63.1657501"
          - label: Nombre del Cementerio
            name: lugarCementerio
            widget: "text"
          - label: URL del lugar del Cementerio
            name: urlLugarCementerio
            widget: string
            default: "https://www.google.com/maps/place/Prever+-+Sal%C3%B3n+Velatorio/@-17.7941441,-63.16884,16z/data=!4m5!3m4!1s0x93f1e85d62ea77cb:0xfd9e12d454893aca!8m2!3d-17.7943484!4d-63.1657501"
  - name: "config"
    label: "Configuración del Sitio"
    identifier_field: config
    delete: false
    files:
      - label: Testimonios
        name: testimonials
        extension: yml
        file: "config/testimonials.yml"
        fields:
          - label: Testimonios
            name: testimonials
            widget: list
            fields:
              - label: Nombre
                name: name
                widget: string
              - label: Texto
                name: text
                widget: text
              - label: Foto
                name: photo
                widget: image
                required: false

      - label: Beneficios de Prever
        name: reasons
        extension: yml
        file: "config/reasons.yml"
        fields:
          - label: Beneficio
            name: reasons
            widget: list
            fields:
              - label: Título
                name: title
                widget: string
              - label: Descripción
                name: description
                widget: text
              - label: Ícono
                name: icon
                hint: ícono en PNG
                widget: image
                required: false
      - label: Galería de imágenes
        name: gallery
        extension: yml
        file: "config/gallery.yml"
        fields:
          - label: Imágenes
            name: gallery
            widget: list
            fields:
              - label: Foto
                name: src
                widget: image
              - label: Título de la foto
                name: title
                widget: string
