# backend:
#   name: test-repo

backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow
media_folder: "/static/img"
public_folder: "/img"
collections:
  - identifier_field: "dataObituarios"
    extension: yml
    label: "Obituarios"
    folder: "src/data/dataObituarios"
    create: true
    slug: "{{slug}}"
    preview: false
    fields:
      - label: "Nombre"
        name: "nombre"
        widget: string
      - label: Fotografía
        name: foto
        widget: image
        required: false
      - label: Fecha de Nacimiento
        name: fechaInicio
        widget: date
        required: false
      - label: Fecha de Fallecimiento
        name: fechaFin
        widget: date
        required: false
      - label: Epitafio
        name: epitafio
        widget: text
        required: false
  - name: "config"
    label: "Configuración del Sitio"
    identifier_field: "config"
    files:
      - label: Testimonios
        extension: yml
        file: "config/testimonials.yml"
        fields:
          - label: Testimonios
            name: testimonial
            widget: list
            fields:
              - label: Nombre
                name: name
                widget: string
              - label: Texto
                name: text
                widget: text
              - label: Foto
                name: photo
                widget: image
                required: false
      - label: Beneficios de Prever
        extension: yml
        file: "config/reasons.yml"
        fields:
          - label: Beneficio
            name: reason
            widget: list
            fields:
              - label: Título
                name: title
                widget: string
              - label: Descripción
                name: description
                widget: text
              - label: Ícono
                name: icon
                hint: ícono en PNG
                widget: image
                required: false
      - label: Galería de imágenes
        extension: yml
        file: "config/gallery.yml"
        fields:
          - label: Imagen
            name: image
            widget: list
            fields:
              - label: Foto
                name: src
                widget: image
              - label: Título de la foto
                name: title
                widget: string
