- parentesco: Abuela
  sexo: 2
  img: /img/abuela.png
- parentesco: Abuelo
  sexo: 1
  img: /img/abuelo.png
- parentesco: Madre
  sexo: 2
  img: /img/abuela.png
- parentesco: Padre
  sexo: 1
  img: /img/abuelo.png
- parentesco: Esposa
  sexo: 2
  img: /img/abuela.png
- parentesco: Conyuge
  sexo: 0
  img: /img/abuela.png
- parentesco: Hijo
  sexo: 0
  img: /img/abuela.png
