- index: 0
  parentesco: Madre
  sexo: 2
  img: /img/mujer2.png
  oppositeIndex: 1
- index: 1
  parentesco: Padre
  sexo: 1
  img: /img/hombre2.png
  oppositeIndex: 0
- index: 2
  parentesco: Abuela
  sexo: 2
  img: /img/abuela.png
  oppositeIndex: 3
- index: 3
  parentesco: Abuelo
  sexo: 1
  img: /img/abuelo.png
  oppositeIndex: 2
- index: 4
  parentesco: Conyuge
  sexo: 0
  img: /img/pareja.png
  oppositeIndex: 5
- index: 5
  parentesco: Hijo
  sexo: 0
  img: /img/chico1.png
  oppositeIndex: 7
- index: 6
  parentesco: Hija
  sexo: 0
  img: /img/chica1.png
  oppositeIndex: 6
