- parentesco: Abuela
  sexo: F
  img: /img/abuela.png
- parentesco: Abuelo
  sexo: M
  img: /img/abuela.png
- parentesco: Madre
  sexo: M
  img: /img/abuela.png
- parentesco: Padre
  sexo: M
  img: /img/abuela.png
- parentesco: Esposa
  sexo: M
  img: /img/abuela.png
- parentesco: Conyuge
  sexo: false
  img: /img/abuela.png
- parentesco: Hijo
  sexo: false
  img: /img/abuela.png
