- parentesco: Madre
  img: /img/mujer2.png
- parentesco: Padre
  img: /img/hombre2.png
- parentesco: Abuela
  img: /img/abuela.png
- parentesco: Abuelo
  img: /img/abuelo.png
- parentesco: Conyuge
  img: /img/pareja.png
- parentesco: Hijo
  img: /img/chico1.png
- parentesco: Hija
  img: /img/chica1.png
- parentesco: Tía | Tío
  img: /img/silueta.png
- parentesco: Sobrina | Sobrino
  img: /img/silueta.png
- parentesco: Hermana | Hermano
  img: /img/silueta.png
- parentesco: Nieta | Nieto
  img: /img/silueta.png
- parentesco: Suegra | Suegro
  img: /img/silueta.png
- parentesco: Primo | Prima
  img: /img/silueta.png
- parentesco: Otro
  img: /img/silueta.png
