gallery:
  - src: "/img/photo1.png"
    title: "Frente"
  - src: "/img/photo2.png"
    title: "Interior"
  - src: "/img/photo3.png"
    title: "Foto 3"
  - src: "/img/photo4.png"
    title: "Foto 4"
  - src: "/img/photo5.png"
    title: "Foto 5"
