reasons:
  - description: 'No importa donde te encuentres, tenemos cobertura en todo el país.'
    icon: /img/bolivia.svg
    title: Cobertura Nacional
  - description: Únicos en el mercado con un Plan de Asistencia Familiar.
    icon: /img/family.svg
    title: Único
  - description: Cuota mínima de 100 bs.
    icon: /img/save-money.svg
    title: Económico
  - description: Ingresan sus padres sin límite de edad.
    icon: /img/accesible.svg
    title: Accesible
