reasons:
  - description: 'No importa donde te encuentres, tenemos cobertura en todo el país.'
    icon: /img/bolivia.svg
    title: Cobertura Nacional
  - description: Este plan te brinda el servicio funerario de manera INMEDIATA
    icon: /img/family.svg
    title: Único
  - description: Con una mínima cuota mensual y sin incurrir en gastos extras.
    icon: /img/save-money.svg
    title: Económico
  - description: >-
      Listos para atenderte sin límite de edad para la permanencia dentro del
      plan.
    icon: /img/accesible.svg
    title: Fásil
