testimonials:
  - name: German Aurelio Quiroz Parra
    photo: /uploads/testimonial-german.jpg
    text: >
      En nombre de toda mi familia quiero transmitirles nuestros agradecimientos
      por la atención recibida en el fallecimiento de mi amado padre, igualmente
      deseamos expresar nuestro agradecimiento a todo el personal que intervino
      en la emotiva despedida, ya que el servicio fue sin prisas y
      permitiéndonos tener una despedida cálida. No hay palabras para expresar
      el agradecimiento a servicios funerarios Prever en estas tristes
      circunstancias para las familias.
  - name: Max Edgar Orellana
    photo: /uploads/testimonial-max.jpg
    text: >
      Una de las instituciones que cumplía mis expectativas fue la funeraria
      Prever por su ubicación y en lo económico ya que tiene los mejores
      precios, sus salas de velación acogedoras, la atención fue muy atenta y
      con cordial bienvenida, sobre todo del sr. Arturo que desde el primer
      momento me dio la seguridad y nos ayudó en todo sin conocernos, agradezco
      a Prever por el servicio prestado y hacer la despedida de mi mamá tan
      emotiva.
  - name: Carmen García Fernández
    photo: /uploads/testimonial-carmen.jpg
    text: >
      Cuando en estas tristes circunstancias para las familias, encuentras
      personas, y un servicio como el que brinda la funeraria Prever, facilitan
      las cosas, pero además apoyan y escuchan, y creo que es lo más importante
      en una despedida. La pérdida de mi esposo fue tan dolorosa porque uno
      quiere que su ser querido este con nosotros para siempre, estoy muy
      agradecida con la empresa Prever por hacer este momento más llevadero.
  - name: ' Mery Carol Wilde'
    photo: /uploads/testimonial-mery.jpg
    text: >-
      Agradezco a cada una de las personas que atendieron de forma muy gentil,
      amable y cariñosa, durante todo el servicio de mi padre en la funeraria
      Prever, quienes fueron muy gentiles y respetuosos, hicieron que este
      momento tan doloroso pasara de manera tranquila y en paz.
  - name: Rita Rivero Román
    photo: /uploads/testimonial-rita.jpg
    text: >-
      Quiero agradecer sinceramente la actitud de respeto y el profesionalismo
      en el servicio de Asistencia Familiar Prever, que desde la primera llamada
      que realice para informar el deceso de mi amado padre José Rivero Coímbra
      (+) la atención fue de manera inmediata, haciéndome sentir absolutamente
      tranquila y lo más confortable para mi familia fue darle su último adiós
      como él se merecía en un lugar acogedor.
