testimonials:
  - name: German Aurelio Quiroz Parra
    photo: /img/german.jpg
    text: >-
      En nombre de toda mi familia quiero transmitirles nuestros agradecimientos
      por la atención recibida en el fallecimiento de mi amado padre, igualmente
      deseamos expresar nuestro agradecimiento a todo el personal que intervino
      en la emotiva despedida, ya que el servicio fue sin prisas y
      permitiéndonos tener una despedida cálida. No hay palabras para expresar
      el agradecimiento a servicios funerarios Prever en estas tristes
      circunstancias para las familias.
  - name: Eva Evangelina Carreon
    photo: >-
      https://prever.com.bo/imagen/productos/51be35312485667c7b7c2cb1f62e0141.jpg
    text: Tienen todos los servicios exequiales que se necesita
  - name: German Monasterio Pacheco
    photo: >-
      https://prever.com.bo/imagen/productos/98eb2f1ec12d0ac2bec384448e654f59.jpg
    text: Su plan es bastante flexible y me da mucha tranquilidad
  - name: Agustin Rueda Escalante
    photo: >-
      https://prever.com.bo/imagen/productos/0f596d79ba39a9f57537d05b290d1408.jpg
    text: Atención empática
