- name: Eva Evangelina Carreon
  text: "Tienen todos los servicios exequiales que se necesita"
  photo: https://prever.com.bo/imagen/productos/51be35312485667c7b7c2cb1f62e0141.jpg
- name: German Monasterio Pacheco
  text: "Su plan es bastante flexible y me da mucha tranquilidad"
  photo: https://prever.com.bo/imagen/productos/98eb2f1ec12d0ac2bec384448e654f59.jpg
- name: Agustin Rueda Escalante
  text: "Atención empática"
  photo: https://prever.com.bo/imagen/productos/0f596d79ba39a9f57537d05b290d1408.jpg
